/*
 * File: app/view/MyPanel1.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('app.view.main.MyPanel1', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.mypanel1',
    controller: 'loginCr',

    requires: [
        'app.model.MyPanel1ViewModel',
        'Ext.form.Label',
        'Ext.button.Button'
    ],

    viewModel: {
        type: 'mypanel1'
    },
    autoShow: true,
    height: 750,
    width: 1356,
    layout: 'absolute',
    bodyStyle: 'background-image: url("http://www.impresionantescr.com/imgs/fondos_f02.jpg");',
    title: 'WELCOME',
    titleAlign: 'center',

    initComponent : function() {
        Ext.apply(this, {
            items: {
                width: 800,
                x:250,
                y:120,
                bodyStyle: 'background-image: url("http://www.impresionantescr.com/imgs/fondos_f02.jpg");',
                bodyPadding: 10,
                items: [{
                    xtype: 'form',
                    bodyStyle: 'background-image: url("http://www.impresionantescr.com/imgs/fondos_f02.jpg");',
                    bbar: ['->',
                        {
                            x: 100,
                            y: 250,
                            height: 270,
                            //style: 'background: url(https://cdn4.iconfinder.com/data/icons/VISTA/project_managment/png/400/deliverables.png);\nbackground-size: 300px 300px;',
                            style: 'background: url(/resources/imagen/usuarios.png);',
                            width: 270,
                            icon: 'products',
                            text: '',
                            handler:'usuarios'
                        },
                        {
                            xtype: 'label',
                            x: 350,
                            y: 440,
                            text: 'USUARIOS'
                        },
                        {

                            x: 470,
                            y: 170,
                            height: 270,
                            itemId: 'mybutton',
                            //style: 'background: url(http://www.fancyicons.com/free-icons/142/network/png/256/user_group_256.png);\nbackground-size: 300px 300px;',
                            style: 'background: url(/resources/imagen/caja.png);',
                            width: 270,
                            icon: 'products',
                            text: '',
                            handler:'productos'
                        }, {
                            xtype: 'label',
                            x: 910,
                            y: 440,
                            text: 'PRODUCTOS'
                        },
                    ],
                }]
            }
        });
        this.callParent();
        }


});